name: Autonomiczny Scraper Newsów

on:
  schedule:
    - cron: '0 */3 * * *' # Odpalaj co 3 godziny
  workflow_dispatch:      # Pozwala odpalić ręcznie przyciskiem

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu z repozytorium
        uses: actions/checkout@v3

      - name: Instalacja Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalacja bibliotek
        run: pip install -r requirements.txt

      - name: Uruchomienie silnika
        run: python main.py

